# dstack server configuration for RunPod integration
# Copy this to ~/.dstack/server/config.yml

projects:
  - name: runpod-ai-tools
    backends:
      - type: runpod
        creds:
          type: api_key
          api_key: ${RUNPOD_API_KEY}
        regions:
          - US-CA-1    # California
          - US-TX-1    # Texas
          - US-NY-1    # New York
          - EU-NO-1    # Norway
          - EU-SE-1    # Sweden
        default_instance_type: "L40S"