projects:
  - name: main
    backends:
      - type: runpod
        creds:
          type: api_key
          api_key: ${RUNPOD_API_KEY}
        community_cloud: false
        regions:
          - US-CA-2
          - US-GA-2
          - US-IL-1
          - US-KS-2
          - US-MO-1
          - US-NC-1
          - US-TX-3
          - US-TX-4
          - US-WA-1
